# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\RSFINAL\yaogan\ui\1\LoadModelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadModelDialog(object):
    def setupUi(self, LoadModelDialog):
        LoadModelDialog.setObjectName("LoadModelDialog")
        LoadModelDialog.resize(417, 280)
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadModelDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 210, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_model_file = QtWidgets.QLabel(LoadModelDialog)
        self.label_model_file.setGeometry(QtCore.QRect(20, 30, 151, 16))
        self.label_model_file.setObjectName("label_model_file")
        self.edit_model_file = QtWidgets.QLineEdit(LoadModelDialog)
        self.edit_model_file.setGeometry(QtCore.QRect(150, 30, 171, 21))
        self.edit_model_file.setObjectName("edit_model_file")
        self.btn_browse_file = QtWidgets.QPushButton(LoadModelDialog)
        self.btn_browse_file.setGeometry(QtCore.QRect(330, 30, 81, 28))
        self.btn_browse_file.setObjectName("btn_browse_file")
        self.label_model_type = QtWidgets.QLabel(LoadModelDialog)
        self.label_model_type.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.label_model_type.setObjectName("label_model_type")
        self.combo_model_type = QtWidgets.QComboBox(LoadModelDialog)
        self.combo_model_type.setGeometry(QtCore.QRect(150, 70, 171, 22))
        self.combo_model_type.setObjectName("combo_model_type")
        self.combo_model_type.addItem("")
        self.combo_model_type.addItem("")
        self.combo_model_type.addItem("")
        self.label_description = QtWidgets.QLabel(LoadModelDialog)
        self.label_description.setGeometry(QtCore.QRect(20, 110, 151, 16))
        self.label_description.setObjectName("label_description")
        self.edit_description = QtWidgets.QLineEdit(LoadModelDialog)
        self.edit_description.setGeometry(QtCore.QRect(150, 110, 171, 21))
        self.edit_description.setObjectName("edit_description")
        self.label_recent_models = QtWidgets.QLabel(LoadModelDialog)
        self.label_recent_models.setGeometry(QtCore.QRect(20, 150, 111, 16))
        self.label_recent_models.setObjectName("label_recent_models")
        self.list_recent_models = QtWidgets.QListWidget(LoadModelDialog)
        self.list_recent_models.setGeometry(QtCore.QRect(150, 150, 221, 31))
        self.list_recent_models.setObjectName("list_recent_models")

        self.retranslateUi(LoadModelDialog)
        self.buttonBox.accepted.connect(LoadModelDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LoadModelDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoadModelDialog)

    def retranslateUi(self, LoadModelDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadModelDialog.setWindowTitle(_translate("LoadModelDialog", "LoadModelDialog"))
        self.label_model_file.setText(_translate("LoadModelDialog", "Model File:"))
        self.btn_browse_file.setText(_translate("LoadModelDialog", "Browse"))
        self.label_model_type.setText(_translate("LoadModelDialog", "Model Type:"))
        self.combo_model_type.setItemText(0, _translate("LoadModelDialog", "SVM"))
        self.combo_model_type.setItemText(1, _translate("LoadModelDialog", "Random Forest"))
        self.combo_model_type.setItemText(2, _translate("LoadModelDialog", "Decison Tree"))
        self.label_description.setText(_translate("LoadModelDialog", "Description:"))
        self.label_recent_models.setText(_translate("LoadModelDialog", "Recent Models:"))
