# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\RSFINAL\yaogan\ui\1\ModelValidationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelValidationDialog(object):
    def setupUi(self, ModelValidationDialog):
        ModelValidationDialog.setObjectName("ModelValidationDialog")
        ModelValidationDialog.resize(458, 293)
        self.buttonBox = QtWidgets.QDialogButtonBox(ModelValidationDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 230, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_model = QtWidgets.QLabel(ModelValidationDialog)
        self.label_model.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label_model.setObjectName("label_model")
        self.label_val_dataset = QtWidgets.QLabel(ModelValidationDialog)
        self.label_val_dataset.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.label_val_dataset.setObjectName("label_val_dataset")
        self.label_val_method = QtWidgets.QLabel(ModelValidationDialog)
        self.label_val_method.setGeometry(QtCore.QRect(20, 110, 161, 16))
        self.label_val_method.setObjectName("label_val_method")
        self.edit_val_dataset = QtWidgets.QLineEdit(ModelValidationDialog)
        self.edit_val_dataset.setGeometry(QtCore.QRect(180, 70, 171, 21))
        self.edit_val_dataset.setObjectName("edit_val_dataset")
        self.btn_browse_dataset = QtWidgets.QPushButton(ModelValidationDialog)
        self.btn_browse_dataset.setGeometry(QtCore.QRect(360, 70, 81, 28))
        self.btn_browse_dataset.setObjectName("btn_browse_dataset")
        self.combo_val_method = QtWidgets.QComboBox(ModelValidationDialog)
        self.combo_val_method.setGeometry(QtCore.QRect(180, 110, 171, 22))
        self.combo_val_method.setObjectName("combo_val_method")
        self.combo_model = QtWidgets.QComboBox(ModelValidationDialog)
        self.combo_model.setGeometry(QtCore.QRect(180, 30, 171, 22))
        self.combo_model.setObjectName("combo_model")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.label_metrics = QtWidgets.QLabel(ModelValidationDialog)
        self.label_metrics.setGeometry(QtCore.QRect(20, 150, 72, 15))
        self.label_metrics.setObjectName("label_metrics")
        self.check_accuracy = QtWidgets.QCheckBox(ModelValidationDialog)
        self.check_accuracy.setGeometry(QtCore.QRect(110, 150, 91, 19))
        self.check_accuracy.setObjectName("check_accuracy")
        self.check_kappa = QtWidgets.QCheckBox(ModelValidationDialog)
        self.check_kappa.setGeometry(QtCore.QRect(220, 150, 91, 19))
        self.check_kappa.setObjectName("check_kappa")
        self.check_matrix = QtWidgets.QCheckBox(ModelValidationDialog)
        self.check_matrix.setGeometry(QtCore.QRect(320, 150, 91, 19))
        self.check_matrix.setObjectName("check_matrix")
        self.edit_output_dir = QtWidgets.QLineEdit(ModelValidationDialog)
        self.edit_output_dir.setGeometry(QtCore.QRect(160, 190, 181, 21))
        self.edit_output_dir.setObjectName("edit_output_dir")
        self.btn_browse_output = QtWidgets.QPushButton(ModelValidationDialog)
        self.btn_browse_output.setGeometry(QtCore.QRect(350, 190, 81, 28))
        self.btn_browse_output.setObjectName("btn_browse_output")
        self.label_output_dir = QtWidgets.QLabel(ModelValidationDialog)
        self.label_output_dir.setGeometry(QtCore.QRect(20, 190, 151, 16))
        self.label_output_dir.setObjectName("label_output_dir")

        self.retranslateUi(ModelValidationDialog)
        self.buttonBox.accepted.connect(ModelValidationDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ModelValidationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModelValidationDialog)

    def retranslateUi(self, ModelValidationDialog):
        _translate = QtCore.QCoreApplication.translate
        ModelValidationDialog.setWindowTitle(_translate("ModelValidationDialog", "ModelValidationDialog"))
        self.label_model.setText(_translate("ModelValidationDialog", "Model Name:"))
        self.label_val_dataset.setText(_translate("ModelValidationDialog", "Validation Dataset:"))
        self.label_val_method.setText(_translate("ModelValidationDialog", "Validation Method:"))
        self.btn_browse_dataset.setText(_translate("ModelValidationDialog", "Browse"))
        self.combo_model.setItemText(0, _translate("ModelValidationDialog", "SVM"))
        self.combo_model.setItemText(1, _translate("ModelValidationDialog", "Random Forest"))
        self.combo_model.setItemText(2, _translate("ModelValidationDialog", "Decison Tree"))
        self.label_metrics.setText(_translate("ModelValidationDialog", "Metrics:"))
        self.check_accuracy.setText(_translate("ModelValidationDialog", "Accuracy"))
        self.check_kappa.setText(_translate("ModelValidationDialog", "Kappa"))
        self.check_matrix.setText(_translate("ModelValidationDialog", "Matrix"))
        self.btn_browse_output.setText(_translate("ModelValidationDialog", "Browse"))
        self.label_output_dir.setText(_translate("ModelValidationDialog", "Output Directory:"))
