# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\RSFINAL\yaogan\ui\1\SaveModelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveModelDialog(object):
    def setupUi(self, SaveModelDialog):
        SaveModelDialog.setObjectName("SaveModelDialog")
        SaveModelDialog.resize(438, 293)
        self.buttonBox = QtWidgets.QDialogButtonBox(SaveModelDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 210, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_model_name = QtWidgets.QLabel(SaveModelDialog)
        self.label_model_name.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label_model_name.setObjectName("label_model_name")
        self.label_save_as = QtWidgets.QLabel(SaveModelDialog)
        self.label_save_as.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.label_save_as.setObjectName("label_save_as")
        self.label_format = QtWidgets.QLabel(SaveModelDialog)
        self.label_format.setGeometry(QtCore.QRect(20, 110, 161, 16))
        self.label_format.setObjectName("label_format")
        self.label_description = QtWidgets.QLabel(SaveModelDialog)
        self.label_description.setGeometry(QtCore.QRect(20, 150, 151, 16))
        self.label_description.setObjectName("label_description")
        self.edit_save_path = QtWidgets.QLineEdit(SaveModelDialog)
        self.edit_save_path.setGeometry(QtCore.QRect(150, 70, 171, 21))
        self.edit_save_path.setObjectName("edit_save_path")
        self.btn_browse_save = QtWidgets.QPushButton(SaveModelDialog)
        self.btn_browse_save.setGeometry(QtCore.QRect(330, 70, 81, 28))
        self.btn_browse_save.setObjectName("btn_browse_save")
        self.edit_description = QtWidgets.QLineEdit(SaveModelDialog)
        self.edit_description.setGeometry(QtCore.QRect(150, 150, 171, 21))
        self.edit_description.setObjectName("edit_description")
        self.combo_format = QtWidgets.QComboBox(SaveModelDialog)
        self.combo_format.setGeometry(QtCore.QRect(150, 110, 171, 22))
        self.combo_format.setObjectName("combo_format")
        self.combo_format.addItem("")
        self.combo_format.addItem("")
        self.combo_format.addItem("")
        self.combo_model_type_2 = QtWidgets.QComboBox(SaveModelDialog)
        self.combo_model_type_2.setGeometry(QtCore.QRect(150, 30, 171, 22))
        self.combo_model_type_2.setObjectName("combo_model_type_2")
        self.combo_model_type_2.addItem("")
        self.combo_model_type_2.addItem("")
        self.combo_model_type_2.addItem("")

        self.retranslateUi(SaveModelDialog)
        self.buttonBox.accepted.connect(SaveModelDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SaveModelDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SaveModelDialog)

    def retranslateUi(self, SaveModelDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveModelDialog.setWindowTitle(_translate("SaveModelDialog", "SaveModelDialog"))
        self.label_model_name.setText(_translate("SaveModelDialog", "Model Name:"))
        self.label_save_as.setText(_translate("SaveModelDialog", "Save As:"))
        self.label_format.setText(_translate("SaveModelDialog", "Format:"))
        self.label_description.setText(_translate("SaveModelDialog", "Description:"))
        self.btn_browse_save.setText(_translate("SaveModelDialog", "Browse"))
        self.combo_format.setItemText(0, _translate("SaveModelDialog", "Pickle (*.pkl)"))
        self.combo_format.setItemText(1, _translate("SaveModelDialog", "HDF5 (*.h5)"))
        self.combo_format.setItemText(2, _translate("SaveModelDialog", "PyTorch (*.pt, *.pth)"))
        self.combo_model_type_2.setItemText(0, _translate("SaveModelDialog", "SVM"))
        self.combo_model_type_2.setItemText(1, _translate("SaveModelDialog", "Random Forest"))
        self.combo_model_type_2.setItemText(2, _translate("SaveModelDialog", "Decison Tree"))
