# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Editing ROI_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditingROIDialog(object):
    def setupUi(self, checkBox_lock):
        checkBox_lock.setObjectName("checkBox_lock")
        checkBox_lock.resize(229, 211)
        self.buttonBox = QtWidgets.QDialogButtonBox(checkBox_lock)
        self.buttonBox.setGeometry(QtCore.QRect(-130, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(checkBox_lock)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_roi = QtWidgets.QComboBox(checkBox_lock)
        self.comboBox_roi.setGeometry(QtCore.QRect(100, 20, 60, 22))
        self.comboBox_roi.setObjectName("comboBox_roi")
        self.label_2 = QtWidgets.QLabel(checkBox_lock)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_name = QtWidgets.QLineEdit(checkBox_lock)
        self.lineEdit_name.setGeometry(QtCore.QRect(100, 60, 71, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_3 = QtWidgets.QLabel(checkBox_lock)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_type = QtWidgets.QLineEdit(checkBox_lock)
        self.label_type.setGeometry(QtCore.QRect(100, 100, 71, 21))
        self.label_type.setObjectName("label_type")
        self.checkBox = QtWidgets.QCheckBox(checkBox_lock)
        self.checkBox.setGeometry(QtCore.QRect(30, 130, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(checkBox_lock)
        self.buttonBox_2.setGeometry(QtCore.QRect(140, 170, 341, 32))
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")

        self.retranslateUi(checkBox_lock)
        self.buttonBox.accepted.connect(checkBox_lock.accept) # type: ignore
        self.buttonBox.rejected.connect(checkBox_lock.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(checkBox_lock)

    def retranslateUi(self, checkBox_lock):
        _translate = QtCore.QCoreApplication.translate
        checkBox_lock.setWindowTitle(_translate("checkBox_lock", "Editing ROI"))
        self.label.setText(_translate("checkBox_lock", "Choose ROI:"))
        self.label_2.setText(_translate("checkBox_lock", "ROI name："))
        self.label_3.setText(_translate("checkBox_lock", "ROI type："))
        self.checkBox.setText(_translate("checkBox_lock", "Lock ROI"))
