# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\yaogan\ui\SampleVerificationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SampleVerifiactionDialog(object):
    def setupUi(self, SampleVerifiactionDialog):
        SampleVerifiactionDialog.setObjectName("SampleVerifiactionDialog")
        SampleVerifiactionDialog.resize(447, 334)
        self.buttonBox = QtWidgets.QDialogButtonBox(SampleVerifiactionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 260, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_sample = QtWidgets.QLabel(SampleVerifiactionDialog)
        self.label_sample.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label_sample.setObjectName("label_sample")
        self.label_method = QtWidgets.QLabel(SampleVerifiactionDialog)
        self.label_method.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.label_method.setObjectName("label_method")
        self.label_sample_size = QtWidgets.QLabel(SampleVerifiactionDialog)
        self.label_sample_size.setGeometry(QtCore.QRect(20, 110, 111, 16))
        self.label_sample_size.setObjectName("label_sample_size")
        self.label_5 = QtWidgets.QLabel(SampleVerifiactionDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 151, 16))
        self.label_5.setObjectName("label_5")
        self.btn_preview = QtWidgets.QPushButton(SampleVerifiactionDialog)
        self.btn_preview.setGeometry(QtCore.QRect(20, 200, 93, 28))
        self.btn_preview.setObjectName("btn_preview")
        self.btn_save_template = QtWidgets.QPushButton(SampleVerifiactionDialog)
        self.btn_save_template.setGeometry(QtCore.QRect(130, 200, 131, 28))
        self.btn_save_template.setObjectName("btn_save_template")
        self.btn_load_template = QtWidgets.QPushButton(SampleVerifiactionDialog)
        self.btn_load_template.setGeometry(QtCore.QRect(270, 200, 121, 28))
        self.btn_load_template.setObjectName("btn_load_template")
        self.lineEdit_sample = QtWidgets.QLineEdit(SampleVerifiactionDialog)
        self.lineEdit_sample.setGeometry(QtCore.QRect(140, 30, 201, 21))
        self.lineEdit_sample.setObjectName("lineEdit_sample")
        self.btn_browse_sample = QtWidgets.QPushButton(SampleVerifiactionDialog)
        self.btn_browse_sample.setGeometry(QtCore.QRect(350, 30, 81, 28))
        self.btn_browse_sample.setObjectName("btn_browse_sample")
        self.spinBox_sample_size = QtWidgets.QSpinBox(SampleVerifiactionDialog)
        self.spinBox_sample_size.setGeometry(QtCore.QRect(140, 110, 51, 22))
        self.spinBox_sample_size.setMinimum(1)
        self.spinBox_sample_size.setMaximum(10000)
        self.spinBox_sample_size.setProperty("value", 99)
        self.spinBox_sample_size.setObjectName("spinBox_sample_size")
        self.lineEdit_outputdir = QtWidgets.QLineEdit(SampleVerifiactionDialog)
        self.lineEdit_outputdir.setGeometry(QtCore.QRect(160, 150, 181, 21))
        self.lineEdit_outputdir.setObjectName("lineEdit_outputdir")
        self.btn_browse_outputdir = QtWidgets.QPushButton(SampleVerifiactionDialog)
        self.btn_browse_outputdir.setGeometry(QtCore.QRect(350, 150, 81, 28))
        self.btn_browse_outputdir.setObjectName("btn_browse_outputdir")
        self.combo_method = QtWidgets.QComboBox(SampleVerifiactionDialog)
        self.combo_method.setGeometry(QtCore.QRect(190, 70, 151, 22))
        self.combo_method.setObjectName("combo_method")
        self.combo_method.addItem("")
        self.combo_method.addItem("")
        self.combo_method.addItem("")

        self.retranslateUi(SampleVerifiactionDialog)
        self.buttonBox.accepted.connect(SampleVerifiactionDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SampleVerifiactionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SampleVerifiactionDialog)

    def retranslateUi(self, SampleVerifiactionDialog):
        _translate = QtCore.QCoreApplication.translate
        SampleVerifiactionDialog.setWindowTitle(_translate("SampleVerifiactionDialog", "Dialog"))
        self.label_sample.setText(_translate("SampleVerifiactionDialog", "Sample File: "))
        self.label_method.setText(_translate("SampleVerifiactionDialog", "Verification Method:"))
        self.label_sample_size.setText(_translate("SampleVerifiactionDialog", "Sample Size: "))
        self.label_5.setText(_translate("SampleVerifiactionDialog", "Output Directory:"))
        self.btn_preview.setText(_translate("SampleVerifiactionDialog", "Preview"))
        self.btn_save_template.setText(_translate("SampleVerifiactionDialog", "Save Template"))
        self.btn_load_template.setText(_translate("SampleVerifiactionDialog", "Load Template"))
        self.btn_browse_sample.setText(_translate("SampleVerifiactionDialog", "Browse"))
        self.btn_browse_outputdir.setText(_translate("SampleVerifiactionDialog", "Browse"))
        self.combo_method.setItemText(0, _translate("SampleVerifiactionDialog", "Random Sampling"))
        self.combo_method.setItemText(1, _translate("SampleVerifiactionDialog", "Systematic"))
        self.combo_method.setItemText(2, _translate("SampleVerifiactionDialog", "Stratified"))
