# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\yaogan\ui\AccuracyReportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccuracyReportDialog(object):
    def setupUi(self, AccuracyReportDialog):
        AccuracyReportDialog.setObjectName("AccuracyReportDialog")
        AccuracyReportDialog.resize(417, 284)
        self.buttonBox = QtWidgets.QDialogButtonBox(AccuracyReportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 220, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_format = QtWidgets.QLabel(AccuracyReportDialog)
        self.label_format.setGeometry(QtCore.QRect(20, 130, 191, 16))
        self.label_format.setObjectName("label_format")
        self.label_outputfile = QtWidgets.QLabel(AccuracyReportDialog)
        self.label_outputfile.setGeometry(QtCore.QRect(20, 170, 151, 16))
        self.label_outputfile.setObjectName("label_outputfile")
        self.lineEdit_outputfile = QtWidgets.QLineEdit(AccuracyReportDialog)
        self.lineEdit_outputfile.setGeometry(QtCore.QRect(150, 170, 171, 21))
        self.lineEdit_outputfile.setObjectName("lineEdit_outputfile")
        self.btn_browse_outputfile = QtWidgets.QPushButton(AccuracyReportDialog)
        self.btn_browse_outputfile.setGeometry(QtCore.QRect(330, 170, 81, 28))
        self.btn_browse_outputfile.setObjectName("btn_browse_outputfile")
        self.check_confusion_matrix = QtWidgets.QCheckBox(AccuracyReportDialog)
        self.check_confusion_matrix.setGeometry(QtCore.QRect(20, 20, 161, 19))
        self.check_confusion_matrix.setObjectName("check_confusion_matrix")
        self.check_overall_accuracy = QtWidgets.QCheckBox(AccuracyReportDialog)
        self.check_overall_accuracy.setGeometry(QtCore.QRect(210, 20, 161, 19))
        self.check_overall_accuracy.setObjectName("check_overall_accuracy")
        self.check_kappa = QtWidgets.QCheckBox(AccuracyReportDialog)
        self.check_kappa.setGeometry(QtCore.QRect(20, 48, 161, 31))
        self.check_kappa.setObjectName("check_kappa")
        self.check_users_accuracy = QtWidgets.QCheckBox(AccuracyReportDialog)
        self.check_users_accuracy.setGeometry(QtCore.QRect(210, 48, 161, 31))
        self.check_users_accuracy.setObjectName("check_users_accuracy")
        self.check_producers_accuracy = QtWidgets.QCheckBox(AccuracyReportDialog)
        self.check_producers_accuracy.setGeometry(QtCore.QRect(20, 90, 181, 19))
        self.check_producers_accuracy.setObjectName("check_producers_accuracy")
        self.check_other = QtWidgets.QCheckBox(AccuracyReportDialog)
        self.check_other.setGeometry(QtCore.QRect(210, 90, 181, 19))
        self.check_other.setText("")
        self.check_other.setObjectName("check_other")
        self.lineEdit_other = QtWidgets.QLineEdit(AccuracyReportDialog)
        self.lineEdit_other.setGeometry(QtCore.QRect(230, 90, 131, 21))
        self.lineEdit_other.setObjectName("lineEdit_other")
        self.combo_format = QtWidgets.QComboBox(AccuracyReportDialog)
        self.combo_format.setGeometry(QtCore.QRect(150, 130, 171, 22))
        self.combo_format.setObjectName("combo_format")
        self.combo_format.addItem("")
        self.combo_format.addItem("")
        self.combo_format.addItem("")

        self.retranslateUi(AccuracyReportDialog)
        self.buttonBox.accepted.connect(AccuracyReportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AccuracyReportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AccuracyReportDialog)

    def retranslateUi(self, AccuracyReportDialog):
        _translate = QtCore.QCoreApplication.translate
        AccuracyReportDialog.setWindowTitle(_translate("AccuracyReportDialog", "Dialog"))
        self.label_format.setText(_translate("AccuracyReportDialog", "Output Format:"))
        self.label_outputfile.setText(_translate("AccuracyReportDialog", "Output File:"))
        self.btn_browse_outputfile.setText(_translate("AccuracyReportDialog", "Browse"))
        self.check_confusion_matrix.setText(_translate("AccuracyReportDialog", "Confusion Matrix"))
        self.check_overall_accuracy.setText(_translate("AccuracyReportDialog", "Overall Accuracy"))
        self.check_kappa.setText(_translate("AccuracyReportDialog", "Kappa Coefficient"))
        self.check_users_accuracy.setText(_translate("AccuracyReportDialog", "User\'s Accuracy"))
        self.check_producers_accuracy.setText(_translate("AccuracyReportDialog", "Producer\'s Accuracy"))
        self.lineEdit_other.setPlaceholderText(_translate("AccuracyReportDialog", "Other metric..."))
        self.combo_format.setItemText(0, _translate("AccuracyReportDialog", "Excel (.xlsx)"))
        self.combo_format.setItemText(1, _translate("AccuracyReportDialog", "CSV (.csv)"))
        self.combo_format.setItemText(2, _translate("AccuracyReportDialog", "TXT (*.txt)"))
