# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\yaogan\ui\ConfusionMatrixDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfusionMatrixDialog(object):
    def setupUi(self, ConfusionMatrixDialog):
        ConfusionMatrixDialog.setObjectName("ConfusionMatrixDialog")
        ConfusionMatrixDialog.resize(417, 359)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfusionMatrixDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 300, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_result = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_result.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label_result.setObjectName("label_result")
        self.label_reference = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_reference.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.label_reference.setObjectName("label_reference")
        self.label_classnum = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_classnum.setGeometry(QtCore.QRect(20, 110, 161, 16))
        self.label_classnum.setObjectName("label_classnum")
        self.label_mask = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_mask.setGeometry(QtCore.QRect(20, 150, 171, 16))
        self.label_mask.setObjectName("label_mask")
        self.label_outputdir = QtWidgets.QLabel(ConfusionMatrixDialog)
        self.label_outputdir.setGeometry(QtCore.QRect(20, 190, 151, 16))
        self.label_outputdir.setObjectName("label_outputdir")
        self.btn_preview = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_preview.setGeometry(QtCore.QRect(20, 240, 93, 28))
        self.btn_preview.setObjectName("btn_preview")
        self.btn_save_template = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_save_template.setGeometry(QtCore.QRect(130, 240, 131, 28))
        self.btn_save_template.setObjectName("btn_save_template")
        self.btn_load_template = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_load_template.setGeometry(QtCore.QRect(270, 240, 121, 28))
        self.btn_load_template.setObjectName("btn_load_template")
        self.lineEdit_result = QtWidgets.QLineEdit(ConfusionMatrixDialog)
        self.lineEdit_result.setGeometry(QtCore.QRect(200, 30, 121, 21))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.btn_browse_result = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_browse_result.setGeometry(QtCore.QRect(330, 30, 81, 28))
        self.btn_browse_result.setObjectName("btn_browse_result")
        self.lineEdit_reference = QtWidgets.QLineEdit(ConfusionMatrixDialog)
        self.lineEdit_reference.setGeometry(QtCore.QRect(150, 70, 171, 21))
        self.lineEdit_reference.setObjectName("lineEdit_reference")
        self.btn_browse_reference = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_browse_reference.setGeometry(QtCore.QRect(330, 70, 81, 28))
        self.btn_browse_reference.setObjectName("btn_browse_reference")
        self.spinBox_classnum = QtWidgets.QSpinBox(ConfusionMatrixDialog)
        self.spinBox_classnum.setGeometry(QtCore.QRect(170, 110, 51, 22))
        self.spinBox_classnum.setMinimum(1)
        self.spinBox_classnum.setProperty("value", 5)
        self.spinBox_classnum.setObjectName("spinBox_classnum")
        self.lineEdit_mask = QtWidgets.QLineEdit(ConfusionMatrixDialog)
        self.lineEdit_mask.setGeometry(QtCore.QRect(190, 150, 131, 21))
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.btn_browse_mask = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_browse_mask.setGeometry(QtCore.QRect(330, 150, 81, 28))
        self.btn_browse_mask.setObjectName("btn_browse_mask")
        self.lineEdit_outputdir = QtWidgets.QLineEdit(ConfusionMatrixDialog)
        self.lineEdit_outputdir.setGeometry(QtCore.QRect(160, 190, 161, 21))
        self.lineEdit_outputdir.setObjectName("lineEdit_outputdir")
        self.btn_browse_outputdir = QtWidgets.QPushButton(ConfusionMatrixDialog)
        self.btn_browse_outputdir.setGeometry(QtCore.QRect(330, 190, 81, 28))
        self.btn_browse_outputdir.setObjectName("btn_browse_outputdir")

        self.retranslateUi(ConfusionMatrixDialog)
        self.buttonBox.accepted.connect(ConfusionMatrixDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ConfusionMatrixDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConfusionMatrixDialog)

    def retranslateUi(self, ConfusionMatrixDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfusionMatrixDialog.setWindowTitle(_translate("ConfusionMatrixDialog", "Dialog"))
        self.label_result.setText(_translate("ConfusionMatrixDialog", "Classification Result:"))
        self.label_reference.setText(_translate("ConfusionMatrixDialog", "Reference Data: "))
        self.label_classnum.setText(_translate("ConfusionMatrixDialog", "Number of Classes:"))
        self.label_mask.setText(_translate("ConfusionMatrixDialog", "Mask File (optional):"))
        self.label_outputdir.setText(_translate("ConfusionMatrixDialog", "Output Directory:   "))
        self.btn_preview.setText(_translate("ConfusionMatrixDialog", "Preview"))
        self.btn_save_template.setText(_translate("ConfusionMatrixDialog", "Save Template"))
        self.btn_load_template.setText(_translate("ConfusionMatrixDialog", "Load Template"))
        self.btn_browse_result.setText(_translate("ConfusionMatrixDialog", "Browse"))
        self.btn_browse_reference.setText(_translate("ConfusionMatrixDialog", "Browse"))
        self.btn_browse_mask.setText(_translate("ConfusionMatrixDialog", "Browse"))
        self.btn_browse_outputdir.setText(_translate("ConfusionMatrixDialog", "Browse"))
