# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\yaogan\ui\OverallAccuracyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OverallAccuracyDialog(object):
    def setupUi(self, OverallAccuracyDialog):
        OverallAccuracyDialog.setObjectName("OverallAccuracyDialog")
        OverallAccuracyDialog.resize(417, 330)
        self.buttonBox = QtWidgets.QDialogButtonBox(OverallAccuracyDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 260, 311, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_result = QtWidgets.QLabel(OverallAccuracyDialog)
        self.label_result.setGeometry(QtCore.QRect(20, 30, 191, 16))
        self.label_result.setObjectName("label_result")
        self.label_reference = QtWidgets.QLabel(OverallAccuracyDialog)
        self.label_reference.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.label_reference.setObjectName("label_reference")
        self.label_classnum = QtWidgets.QLabel(OverallAccuracyDialog)
        self.label_classnum.setGeometry(QtCore.QRect(20, 110, 161, 16))
        self.label_classnum.setObjectName("label_classnum")
        self.label_outputdir = QtWidgets.QLabel(OverallAccuracyDialog)
        self.label_outputdir.setGeometry(QtCore.QRect(20, 150, 151, 16))
        self.label_outputdir.setObjectName("label_outputdir")
        self.btn_preview = QtWidgets.QPushButton(OverallAccuracyDialog)
        self.btn_preview.setGeometry(QtCore.QRect(20, 200, 93, 28))
        self.btn_preview.setObjectName("btn_preview")
        self.btn_save_template = QtWidgets.QPushButton(OverallAccuracyDialog)
        self.btn_save_template.setGeometry(QtCore.QRect(130, 200, 131, 28))
        self.btn_save_template.setObjectName("btn_save_template")
        self.btn_load_template = QtWidgets.QPushButton(OverallAccuracyDialog)
        self.btn_load_template.setGeometry(QtCore.QRect(270, 200, 121, 28))
        self.btn_load_template.setObjectName("btn_load_template")
        self.lineEdit_result = QtWidgets.QLineEdit(OverallAccuracyDialog)
        self.lineEdit_result.setGeometry(QtCore.QRect(200, 30, 121, 21))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.btn_browse_result = QtWidgets.QPushButton(OverallAccuracyDialog)
        self.btn_browse_result.setGeometry(QtCore.QRect(330, 30, 81, 28))
        self.btn_browse_result.setObjectName("btn_browse_result")
        self.lineEdit_reference = QtWidgets.QLineEdit(OverallAccuracyDialog)
        self.lineEdit_reference.setGeometry(QtCore.QRect(150, 70, 171, 21))
        self.lineEdit_reference.setObjectName("lineEdit_reference")
        self.btn_browse_reference = QtWidgets.QPushButton(OverallAccuracyDialog)
        self.btn_browse_reference.setGeometry(QtCore.QRect(330, 70, 81, 28))
        self.btn_browse_reference.setObjectName("btn_browse_reference")
        self.spinBox_classnum = QtWidgets.QSpinBox(OverallAccuracyDialog)
        self.spinBox_classnum.setGeometry(QtCore.QRect(170, 110, 51, 22))
        self.spinBox_classnum.setMinimum(1)
        self.spinBox_classnum.setProperty("value", 5)
        self.spinBox_classnum.setObjectName("spinBox_classnum")
        self.lineEdit_outputdir = QtWidgets.QLineEdit(OverallAccuracyDialog)
        self.lineEdit_outputdir.setGeometry(QtCore.QRect(160, 150, 161, 21))
        self.lineEdit_outputdir.setObjectName("lineEdit_outputdir")
        self.btn_browse_outputdir = QtWidgets.QPushButton(OverallAccuracyDialog)
        self.btn_browse_outputdir.setGeometry(QtCore.QRect(330, 150, 81, 28))
        self.btn_browse_outputdir.setObjectName("btn_browse_outputdir")

        self.retranslateUi(OverallAccuracyDialog)
        self.buttonBox.accepted.connect(OverallAccuracyDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(OverallAccuracyDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OverallAccuracyDialog)

    def retranslateUi(self, OverallAccuracyDialog):
        _translate = QtCore.QCoreApplication.translate
        OverallAccuracyDialog.setWindowTitle(_translate("OverallAccuracyDialog", "Dialog"))
        self.label_result.setText(_translate("OverallAccuracyDialog", "Classification Result:"))
        self.label_reference.setText(_translate("OverallAccuracyDialog", "Reference Data: "))
        self.label_classnum.setText(_translate("OverallAccuracyDialog", "Number of Classes:"))
        self.label_outputdir.setText(_translate("OverallAccuracyDialog", "Output Directory:   "))
        self.btn_preview.setText(_translate("OverallAccuracyDialog", "Preview"))
        self.btn_save_template.setText(_translate("OverallAccuracyDialog", "Save Template"))
        self.btn_load_template.setText(_translate("OverallAccuracyDialog", "Load Template"))
        self.btn_browse_result.setText(_translate("OverallAccuracyDialog", "Browse"))
        self.btn_browse_reference.setText(_translate("OverallAccuracyDialog", "Browse"))
        self.btn_browse_outputdir.setText(_translate("OverallAccuracyDialog", "Browse"))
