# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Save Model As_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveModelAsDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(264, 203)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_traingsample_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_4.setGeometry(QtCore.QRect(110, 20, 71, 21))
        self.lineEdit_traingsample_4.setObjectName("lineEdit_traingsample_4")
        self.lineEdit_traingsample_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_9.setGeometry(QtCore.QRect(110, 60, 71, 21))
        self.lineEdit_traingsample_9.setReadOnly(True)
        self.lineEdit_traingsample_9.setObjectName("lineEdit_traingsample_9")
        self.button_browse_9 = QtWidgets.QPushButton(Dialog)
        self.button_browse_9.setGeometry(QtCore.QRect(190, 70, 41, 16))
        self.button_browse_9.setObjectName("button_browse_9")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(30, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 41, 9))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 100, 60, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(30, 140, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Cancel_8 = QtWidgets.QPushButton(Dialog)
        self.Cancel_8.setGeometry(QtCore.QRect(180, 170, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_8.setFont(font)
        self.Cancel_8.setObjectName("Cancel_8")
        self.Run_8 = QtWidgets.QPushButton(Dialog)
        self.Run_8.setGeometry(QtCore.QRect(120, 170, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_8.setFont(font)
        self.Run_8.setObjectName("Run_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Model name:"))
        self.button_browse_9.setText(_translate("Dialog", "Browse"))
        self.label_22.setText(_translate("Dialog", "Save directory:"))
        self.label.setText(_translate("Dialog", "Format:"))
        self.comboBox.setItemText(0, _translate("Dialog", ".pkl"))
        self.comboBox.setItemText(1, _translate("Dialog", ".h5"))
        self.comboBox.setItemText(2, _translate("Dialog", ".onnx"))
        self.comboBox.setItemText(3, _translate("Dialog", ".json"))
        self.checkBox.setText(_translate("Dialog", "Overwrite if file exists"))
        self.Cancel_8.setText(_translate("Dialog", "Cancel"))
        self.Run_8.setText(_translate("Dialog", "Save"))
