# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\SVM_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SVMDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(282, 209)
        self.button_browse = QtWidgets.QPushButton(Dialog)
        self.button_browse.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.button_browse.setObjectName("button_browse")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_traingsample = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample.setGeometry(QtCore.QRect(130, 20, 71, 21))
        self.lineEdit_traingsample.setObjectName("lineEdit_traingsample")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 60, 60, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setCurrentText("Linear")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(130, 100, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(130, 140, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.Run_3 = QtWidgets.QPushButton(Dialog)
        self.Run_3.setGeometry(QtCore.QRect(130, 180, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_3.setFont(font)
        self.Run_3.setObjectName("Run_3")
        self.Cancel_3 = QtWidgets.QPushButton(Dialog)
        self.Cancel_3.setGeometry(QtCore.QRect(200, 180, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_3.setFont(font)
        self.Cancel_3.setObjectName("Cancel_3")

        self.retranslateUi(Dialog)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SVM"))
        self.button_browse.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Training Sample File："))
        self.label_3.setText(_translate("Dialog", "Kernel Type"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Linear"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "RBF"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Polynomial"))
        self.label_2.setText(_translate("Dialog", "Penalty Parameter (C)"))
        self.label_4.setText(_translate("Dialog", "Gamma"))
        self.Run_3.setText(_translate("Dialog", "Run"))
        self.Cancel_3.setText(_translate("Dialog", "Cancel"))
