# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Denoising_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DenoisingDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(315, 167)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(30, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_traingsample_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_7.setGeometry(QtCore.QRect(160, 20, 71, 21))
        self.lineEdit_traingsample_7.setObjectName("lineEdit_traingsample_7")
        self.button_browse_7 = QtWidgets.QPushButton(Dialog)
        self.button_browse_7.setGeometry(QtCore.QRect(240, 30, 41, 16))
        self.button_browse_7.setObjectName("button_browse_7")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 60, 121, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(30, 100, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.spinBox_9 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_9.setGeometry(QtCore.QRect(160, 100, 41, 21))
        self.spinBox_9.setMinimum(1)
        self.spinBox_9.setMaximum(50)
        self.spinBox_9.setProperty("value", 5)
        self.spinBox_9.setObjectName("spinBox_9")
        self.Cancel_8 = QtWidgets.QPushButton(Dialog)
        self.Cancel_8.setGeometry(QtCore.QRect(230, 130, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_8.setFont(font)
        self.Cancel_8.setObjectName("Cancel_8")
        self.Run_8 = QtWidgets.QPushButton(Dialog)
        self.Run_8.setGeometry(QtCore.QRect(170, 130, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_8.setFont(font)
        self.Run_8.setObjectName("Run_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Denoising"))
        self.label_12.setText(_translate("Dialog", "Input Classification Result："))
        self.button_browse_7.setText(_translate("Dialog", "Browse"))
        self.label_13.setText(_translate("Dialog", "Denoising Method:"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Morphological Opening"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Morphological Closing"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Bilateral Filter"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Non-Local Means"))
        self.label_14.setText(_translate("Dialog", "Parameter (if applicable):"))
        self.Cancel_8.setText(_translate("Dialog", "Cancel"))
        self.Run_8.setText(_translate("Dialog", "Run"))
