# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\CreatePolygon_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatePolygonDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(349, 256)
        self.AddVertex = QtWidgets.QPushButton(Dialog)
        self.AddVertex.setGeometry(QtCore.QRect(270, 100, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.AddVertex.setFont(font)
        self.AddVertex.setObjectName("AddVertex")
        self.lineEdit_polygonName = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_polygonName.setGeometry(QtCore.QRect(110, 20, 71, 21))
        self.lineEdit_polygonName.setObjectName("lineEdit_polygonName")
        self.DeleteVertex = QtWidgets.QPushButton(Dialog)
        self.DeleteVertex.setGeometry(QtCore.QRect(270, 130, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.DeleteVertex.setFont(font)
        self.DeleteVertex.setObjectName("DeleteVertex")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox_2.setGeometry(QtCore.QRect(-180, 220, 511, 32))
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tableWidget_vertices = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_vertices.setGeometry(QtCore.QRect(30, 50, 231, 161))
        self.tableWidget_vertices.setObjectName("tableWidget_vertices")
        self.tableWidget_vertices.setColumnCount(0)
        self.tableWidget_vertices.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CreatePolygon"))
        self.AddVertex.setText(_translate("Dialog", "Add Vertex"))
        self.DeleteVertex.setText(_translate("Dialog", "Delete Vertex"))
        self.label_6.setText(_translate("Dialog", "Polygon name:"))
