# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Create Point_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatePointDialog(object):
    def setupUi(self, lineEdit_pointName):
        lineEdit_pointName.setObjectName("lineEdit_pointName")
        lineEdit_pointName.resize(216, 204)
        self.label_2 = QtWidgets.QLabel(lineEdit_pointName)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_pointName_2 = QtWidgets.QLineEdit(lineEdit_pointName)
        self.lineEdit_pointName_2.setGeometry(QtCore.QRect(80, 20, 71, 21))
        self.lineEdit_pointName_2.setObjectName("lineEdit_pointName_2")
        self.xcoordinate = QtWidgets.QLabel(lineEdit_pointName)
        self.xcoordinate.setGeometry(QtCore.QRect(20, 50, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.xcoordinate.setFont(font)
        self.xcoordinate.setObjectName("xcoordinate")
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(lineEdit_pointName)
        self.doubleSpinBox_x.setGeometry(QtCore.QRect(90, 60, 62, 22))
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.ycoordinate = QtWidgets.QLabel(lineEdit_pointName)
        self.ycoordinate.setGeometry(QtCore.QRect(20, 90, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.ycoordinate.setFont(font)
        self.ycoordinate.setObjectName("ycoordinate")
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(lineEdit_pointName)
        self.doubleSpinBox_y.setGeometry(QtCore.QRect(90, 100, 62, 22))
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.pushButton = QtWidgets.QPushButton(lineEdit_pointName)
        self.pushButton.setGeometry(QtCore.QRect(60, 150, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(lineEdit_pointName)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 150, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(lineEdit_pointName)
        QtCore.QMetaObject.connectSlotsByName(lineEdit_pointName)

    def retranslateUi(self, lineEdit_pointName):
        _translate = QtCore.QCoreApplication.translate
        lineEdit_pointName.setWindowTitle(_translate("lineEdit_pointName", "Create Point"))
        self.label_2.setText(_translate("lineEdit_pointName", "Point name:"))
        self.xcoordinate.setText(_translate("lineEdit_pointName", "X Coordinate："))
        self.ycoordinate.setText(_translate("lineEdit_pointName", "Y Coordinate："))
        self.pushButton.setText(_translate("lineEdit_pointName", "Add point"))
        self.pushButton_2.setText(_translate("lineEdit_pointName", "Cancel"))
