# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\CreatePolyline_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatePolylineDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(347, 247)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_polylineName = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_polylineName.setGeometry(QtCore.QRect(110, 20, 71, 21))
        self.lineEdit_polylineName.setObjectName("lineEdit_polylineName")
        self.tableWidget_points = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_points.setGeometry(QtCore.QRect(30, 50, 231, 161))
        self.tableWidget_points.setObjectName("tableWidget_points")
        self.tableWidget_points.setColumnCount(0)
        self.tableWidget_points.setRowCount(0)
        self.AddVertex = QtWidgets.QPushButton(Dialog)
        self.AddVertex.setGeometry(QtCore.QRect(270, 100, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.AddVertex.setFont(font)
        self.AddVertex.setObjectName("AddVertex")
        self.DeleteVertex = QtWidgets.QPushButton(Dialog)
        self.DeleteVertex.setGeometry(QtCore.QRect(270, 130, 61, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.DeleteVertex.setFont(font)
        self.DeleteVertex.setObjectName("DeleteVertex")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-180, 220, 511, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CreatePolyline"))
        self.label_5.setText(_translate("Dialog", "Polyline name:"))
        self.AddVertex.setText(_translate("Dialog", "Add Vertex"))
        self.DeleteVertex.setText(_translate("Dialog", "Delete Vertex"))
