# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Decision Tree_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DecisionTreeDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(275, 176)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_traingsample_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_2.setGeometry(QtCore.QRect(130, 20, 71, 21))
        self.lineEdit_traingsample_2.setObjectName("lineEdit_traingsample_2")
        self.button_browse_2 = QtWidgets.QPushButton(Dialog)
        self.button_browse_2.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.button_browse_2.setObjectName("button_browse_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(130, 60, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 100, 42, 22))
        self.spinBox_2.setMinimum(2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.Cancel_4 = QtWidgets.QPushButton(Dialog)
        self.Cancel_4.setGeometry(QtCore.QRect(200, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_4.setFont(font)
        self.Cancel_4.setObjectName("Cancel_4")
        self.Run_4 = QtWidgets.QPushButton(Dialog)
        self.Run_4.setGeometry(QtCore.QRect(130, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_4.setFont(font)
        self.Run_4.setObjectName("Run_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Decision Tree"))
        self.label_5.setText(_translate("Dialog", "Training Sample File："))
        self.button_browse_2.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Max Depth"))
        self.label_2.setText(_translate("Dialog", "Min Samples Split"))
        self.Cancel_4.setText(_translate("Dialog", "Cancel"))
        self.Run_4.setText(_translate("Dialog", "Run"))
