# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Minimum Distance_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MinimumDistanceDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(269, 134)
        self.lineEdit_traingsample_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_2.setGeometry(QtCore.QRect(130, 20, 71, 21))
        self.lineEdit_traingsample_2.setObjectName("lineEdit_traingsample_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button_browse_2 = QtWidgets.QPushButton(Dialog)
        self.button_browse_2.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.button_browse_2.setObjectName("button_browse_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(130, 60, 62, 22))
        self.doubleSpinBox.setMaximum(9999.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.Run_2 = QtWidgets.QPushButton(Dialog)
        self.Run_2.setGeometry(QtCore.QRect(130, 100, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_2.setFont(font)
        self.Run_2.setObjectName("Run_2")
        self.Cancel_2 = QtWidgets.QPushButton(Dialog)
        self.Cancel_2.setGeometry(QtCore.QRect(200, 100, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_2.setFont(font)
        self.Cancel_2.setObjectName("Cancel_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Minimum Distance"))
        self.label_3.setText(_translate("Dialog", "Training Sample File："))
        self.button_browse_2.setText(_translate("Dialog", "Browse"))
        self.label.setText(_translate("Dialog", "Distance Threshold"))
        self.Run_2.setText(_translate("Dialog", "Run"))
        self.Cancel_2.setText(_translate("Dialog", "Cancel"))
