# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Random Forest_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RandomForestDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(283, 172)
        self.lineEdit_traingsample_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_3.setGeometry(QtCore.QRect(130, 20, 71, 21))
        self.lineEdit_traingsample_3.setObjectName("lineEdit_traingsample_3")
        self.button_browse_3 = QtWidgets.QPushButton(Dialog)
        self.button_browse_3.setGeometry(QtCore.QRect(210, 30, 41, 16))
        self.button_browse_3.setObjectName("button_browse_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(130, 60, 42, 22))
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(130, 100, 42, 22))
        self.spinBox_3.setMinimum(2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.Cancel_5 = QtWidgets.QPushButton(Dialog)
        self.Cancel_5.setGeometry(QtCore.QRect(200, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_5.setFont(font)
        self.Cancel_5.setObjectName("Cancel_5")
        self.Run_5 = QtWidgets.QPushButton(Dialog)
        self.Run_5.setGeometry(QtCore.QRect(130, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_5.setFont(font)
        self.Run_5.setObjectName("Run_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Random Forest "))
        self.button_browse_3.setText(_translate("Dialog", "Browse"))
        self.label_6.setText(_translate("Dialog", "Training Sample File："))
        self.label_3.setText(_translate("Dialog", "Number of Trees"))
        self.label_4.setText(_translate("Dialog", "Min Samples Split"))
        self.Cancel_5.setText(_translate("Dialog", "Cancel"))
        self.Run_5.setText(_translate("Dialog", "Run"))
