# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\KMeans_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KMeansDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(272, 190)
        self.button_browse_4 = QtWidgets.QPushButton(Dialog)
        self.button_browse_4.setGeometry(QtCore.QRect(200, 30, 41, 16))
        self.button_browse_4.setObjectName("button_browse_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_traingsample_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_4.setGeometry(QtCore.QRect(120, 20, 71, 21))
        self.lineEdit_traingsample_4.setReadOnly(True)
        self.lineEdit_traingsample_4.setObjectName("lineEdit_traingsample_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.spinBox_4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(120, 60, 41, 21))
        self.spinBox_4.setMinimum(2)
        self.spinBox_4.setMaximum(100)
        self.spinBox_4.setProperty("value", 5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 100, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox_5 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(120, 100, 41, 21))
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(1000)
        self.spinBox_5.setProperty("value", 100)
        self.spinBox_5.setObjectName("spinBox_5")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(30, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Cancel_6 = QtWidgets.QPushButton(Dialog)
        self.Cancel_6.setGeometry(QtCore.QRect(190, 160, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_6.setFont(font)
        self.Cancel_6.setObjectName("Cancel_6")
        self.Run_6 = QtWidgets.QPushButton(Dialog)
        self.Run_6.setGeometry(QtCore.QRect(130, 160, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_6.setFont(font)
        self.Run_6.setObjectName("Run_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "KMeans"))
        self.button_browse_4.setText(_translate("Dialog", "Browse"))
        self.label_7.setText(_translate("Dialog", "Input Image File:"))
        self.label_8.setText(_translate("Dialog", "Number of Clusters"))
        self.label_9.setText(_translate("Dialog", "Max Iterations"))
        self.checkBox.setText(_translate("Dialog", "Initialize Randomly"))
        self.Cancel_6.setText(_translate("Dialog", "Cancel"))
        self.Run_6.setText(_translate("Dialog", "Run"))
