# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Custom color_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomColorDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(299, 178)
        self.button_browse_4 = QtWidgets.QPushButton(Dialog)
        self.button_browse_4.setGeometry(QtCore.QRect(230, 30, 41, 16))
        self.button_browse_4.setObjectName("button_browse_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_traingsample_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_4.setGeometry(QtCore.QRect(150, 20, 71, 21))
        self.lineEdit_traingsample_4.setObjectName("lineEdit_traingsample_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.button_browse_5 = QtWidgets.QPushButton(Dialog)
        self.button_browse_5.setGeometry(QtCore.QRect(230, 70, 41, 16))
        self.button_browse_5.setObjectName("button_browse_5")
        self.lineEdit_traingsample_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_5.setGeometry(QtCore.QRect(150, 60, 71, 21))
        self.lineEdit_traingsample_5.setObjectName("lineEdit_traingsample_5")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Run_6 = QtWidgets.QPushButton(Dialog)
        self.Run_6.setGeometry(QtCore.QRect(150, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_6.setFont(font)
        self.Run_6.setObjectName("Run_6")
        self.Cancel_9 = QtWidgets.QPushButton(Dialog)
        self.Cancel_9.setGeometry(QtCore.QRect(220, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_9.setFont(font)
        self.Cancel_9.setObjectName("Cancel_9")
        self.Run_9 = QtWidgets.QPushButton(Dialog)
        self.Run_9.setGeometry(QtCore.QRect(160, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_9.setFont(font)
        self.Run_9.setObjectName("Run_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Custom Color"))
        self.button_browse_4.setText(_translate("Dialog", "Browse"))
        self.label_7.setText(_translate("Dialog", "Classification Result File:"))
        self.label_8.setText(_translate("Dialog", "Color Map File (optional):"))
        self.button_browse_5.setText(_translate("Dialog", "Browse"))
        self.label_9.setText(_translate("Dialog", "Default Color:"))
        self.Run_6.setText(_translate("Dialog", "Choose Color"))
        self.Cancel_9.setText(_translate("Dialog", "Cancel"))
        self.Run_9.setText(_translate("Dialog", "Apply"))
