# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\11259\Desktop\ui\Smooth Processing_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SmoothProcessingDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(297, 175)
        self.lineEdit_traingsample_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_traingsample_6.setGeometry(QtCore.QRect(150, 30, 71, 21))
        self.lineEdit_traingsample_6.setObjectName("lineEdit_traingsample_6")
        self.button_browse_6 = QtWidgets.QPushButton(Dialog)
        self.button_browse_6.setGeometry(QtCore.QRect(230, 40, 41, 16))
        self.button_browse_6.setObjectName("button_browse_6")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 70, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.spinBox_8 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_8.setGeometry(QtCore.QRect(90, 110, 41, 21))
        self.spinBox_8.setMinimum(1)
        self.spinBox_8.setMaximum(21)
        self.spinBox_8.setProperty("value", 3)
        self.spinBox_8.setObjectName("spinBox_8")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(20, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.Cancel_8 = QtWidgets.QPushButton(Dialog)
        self.Cancel_8.setGeometry(QtCore.QRect(220, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Cancel_8.setFont(font)
        self.Cancel_8.setObjectName("Cancel_8")
        self.Run_8 = QtWidgets.QPushButton(Dialog)
        self.Run_8.setGeometry(QtCore.QRect(160, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Run_8.setFont(font)
        self.Run_8.setObjectName("Run_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Smooth Processing "))
        self.button_browse_6.setText(_translate("Dialog", "Browse"))
        self.label_10.setText(_translate("Dialog", "Input Classification Result："))
        self.label_11.setText(_translate("Dialog", "Smoothing Method:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Median Filter"))
        self.comboBox.setItemText(1, _translate("Dialog", "Mean Filter"))
        self.comboBox.setItemText(2, _translate("Dialog", "Gaussian Filter"))
        self.label_20.setText(_translate("Dialog", "Kernel Size:"))
        self.Cancel_8.setText(_translate("Dialog", "Cancel"))
        self.Run_8.setText(_translate("Dialog", "Run"))
